  services:
    postgres:
      image: postgres:latest
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: superadmin
        POSTGRES_PASSWORD: illdoitmyself
        POSTGRES_DB: crypto-db
      volumes:
        - pg_data:/var/lib/postgresql/data


    redis:
      image: redis:latest
      restart: always
      volumes:
        - pg_data:/var/lib/redis/cache-data
      ports:
        - "6379:6379"

    app:
      build: .
      depends_on:
        - postgres
        - redis
      volumes:
      - .:/app
      working_dir: /app
      command: python main.py
      

  volumes:
    pg_data:
    redis_data: