"""Добавление столбца salt в таблицу users и уничтожение столбца password

Revision ID: 7332de079d22
Revises: f0376f2c28ed
Create Date: 2025-02-10 22:25:23.360428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7332de079d22'
down_revision: Union[str, None] = 'f0376f2c28ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.TEXT(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###
