"""Checkpoints were made

Revision ID: b355058a590e
Revises: 7332de079d22
Create Date: 2025-02-12 13:11:10.311279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b355058a590e'
down_revision: Union[str, None] = '7332de079d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkpoints', sa.Column('created_at', postgresql.TIME(), nullable=True))
    op.add_column('checkpoints', sa.Column('session_count', sa.INTEGER(), nullable=True))
    op.add_column('checkpoints', sa.Column('number', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkpoints', 'number')
    op.drop_column('checkpoints', 'session_count')
    op.drop_column('checkpoints', 'created_at')
    # ### end Alembic commands ###
